fixed stuff w room requests and fake data ahhhhh
hack4impact/ronald-mcdonald-house pull request #5
Opened 2019-10-19 17:41 UTC by jamiewang98

thanks to nina 😻

2019-10-19 19:29 UTC, katiejiang requested changes

2019-10-19 19:29 UTC, katiejiang commented on app/models/room_request.py
> +                        **kwargs)
I think we should add fake data for all the columns! That way we can more easily test front-end and we don't have to manually enter this data everytime through `**kwargs`.

2019-10-21 22:33 UTC, katiejiang commented on app/models/room_request.py
> +                        primary_language = random.choice(["English", "Spanish""]),
You have an extra quotation mark here!

2019-10-21 22:34 UTC, katiejiang commented on app/__init__.py
> +    "{ODBC Driver 17 for SQL Server}",
Why is this getting changed?

2019-10-21 23:05 UTC, jamiewang98 commented on app/__init__.py
> +    "{ODBC Driver 17 for SQL Server}",
azure...??

2019-10-25 02:39 UTC, merged